### ISSUE TITLE
Should we make the Github link open in a new tab?

### ISSUE THREAD

**Issue by AMHOL** [dry-rb/dry-rb.org#10]
It currently redirects the user away from the site, should we use a blank target?

**Comment by timriley** [comment]
I think developers will know what they'll want to do here, and we can just leave the links as is. (I'm generally against opening new Windows/tabs via links unless really necessary) 






On Mon, Mar 14, 2016 at 12:00 PM -0700, "Andy Holland" <notifications@github.com> wrote:












It currently redirects the user away from the site, should we use a blank target?

**Comment by solnic** [comment]
I just reacted to this :joy:

**Comment by AMHOL** [comment]
Cool :joy:
