### ISSUE TITLE
Semantic Versioning for all dry-rb gems

### ISSUE THREAD

**Issue by sahal2080** [dry-rb/dry-rb.org#112]
Along the lines of #59, it'd be structurally more beneficial if the dry-rb ecosystem started following [SemVer](http://semver.org/). Personally, what matter most are the [API changes](http://semver.org/#if-even-the-tiniest-backwards-incompatible-changes-to-the-public-api-require-a-major-version-bump-wont-i-end-up-at-version-4200-very-rapidly) parts. It's understandable for an open-source and a nascent project to keep changing without proper notification and documentation. SemVer here will helps us (in the outside) be in control of how much exposure to changes we want in each project we work on.

I sadly know that takes away the sexy *1.00* milestone. But hey, this way you're more *agile* which is still sexy, I hope.

P.s. I didn't know where to post this issue so I hope I made the right call by submitting it here. Cheers.

**Comment by solnic** [comment]
We follow SemVer, but at the moment all dry-rb gems are in beta phase. We typically bump minor version number when we break some APIs or change behavior in any backward-incompatible way. Once a gem hits 1.0.0, we'll be bumping major numbers.

**Comment by sahal2080** [comment]
Taken directly from SemVer link above (em­pha­sis is mine):

> If even the tiniest backwards incompatible changes to the public API require a major version bump, won’t I end up at version 42.0.0 very rapidly?

> This is a question of **responsible development** and foresight. Incompatible changes should not be introduced lightly to software that has a lot of dependent code. The cost that must be incurred to upgrade can be significant. Having to bump major versions to release incompatible changes means you’ll think through the impact of your changes, and evaluate the **cost/benefit** ratio involved.

Message conveyed.
