### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-rb.org#133]
The current [dry-rb.org homepage](http://dry-rb.org) could do better to introduce people to dry-rb and entice them to try it.

I’d like to make this better.  I think an improved homepage could offer:

- A more compelling one-line pitch
- A better statement of our founding principles (replacing the mostly-empty non-intrusive/flexible/fast section on the current site). This could go 2 ways, I think: either collapse these into a single, supporting sentence (or two) to the one-line pitch, or try and expand on these as multiple separate points with a supporting sentence for each. These'd need different design treatments, obviously. I think perhaps the "supporting sentence" might be better, and we can link off to a full "principles" page later if we wanted to. 
- A description of the 2 possible “pathways” you can follow in adopting dry-rb:
	1. dry-rb as foundation of your app (“go all in”)
	2. or to enhance parts of your existing app (“pick and choose”)
- Short code examples for a few important use cases
	- validation
	- types?
	- dry-system + auto\_inject
	- dry-monads + matcher
- Big fat links/buttons to the list of gems + (upcoming) guides page

In doing these, I think we could probably ditch the gem list on the home page and just make the /gems page better (will file a separate issue about that).

What's the work involved here? Obviously there's some content to be written, but I think at the same time we could start work on some new visual design structure to house it.

<hr>

FWIW, I surveyed some other OSS project homepages in thinking about this:

[Ember.js](http://emberjs.com/ "Ember.js - A framework for creating ambitious web applications."): probably the best example of the kind of thing I’d like to see us have. Visually nice and still has a decent intro and code samples.

[React](https://facebook.github.io/react/ "A JavaScript library for building user interfaces - React"): less visually impressive than Ember but a decent combo of intro pitch + code examples. This is probably closer to what we have now and wouldn’t be a bad place to get to :)

[Angular](https://angular.io/ "One framework. - Angular"): So… material. TBH this feels a little light-on for a homepage. I’d rather us supply visitors with some more info.

[Mithril](http://mithril.js.org/ "Mithril"): Not visually impressive, but it has a clear little “pitch” section up-front, which isn’t bad.

[Ruby on Rails](http://rubyonrails.org/ "Ruby on Rails"): This is a bit light on details, which Rails can get away with, but we need to give more info to get people to consider dry-rb, IMO. Also, I’m not sold on the video as introductory material. Most times I won’t click.

**Comment by GustavoCaso** [comment]
Fixed by https://github.com/dry-rb/dry-rb.org/pull/154
