### ISSUE TITLE
Update gem page titles to indicate gems

### ISSUE THREAD

**Issue by AMHOL** [dry-rb/dry-rb.org#21]
Currently the gem page titles are the same as the h1 tags, it would be good to indicate which gem docs you're reading

**Comment by timriley** [comment]
Yeah, I agree. I reckon we want something like this:

![screen shot 2016-03-16 at 8 34 20 pm](https://cloud.githubusercontent.com/assets/3134/13807881/98e84a22-ebb7-11e5-90db-3e602cdce598.png)

@jasminwong or @andyicelab, perhaps you could help?

**Comment by AMHOL** [comment]
I actually meant the <title> tag, but I think what you've suggested there looks good too @timriley

**Comment by timriley** [comment]
Oh! haha, let's do both then :)

**Comment by timriley** [comment]
Fixed by #32
