### ISSUE TITLE
http redirect https

### ISSUE THREAD

**Issue by jychen7** [dry-rb/dry-rb.org#261]
**Description**

Both http and https are accessible, but Chrome shows "Not Secure" for http

![image](https://user-images.githubusercontent.com/663949/43268514-703a3a9a-9123-11e8-9ebe-8c75c7b1d21f.png)

![image](https://user-images.githubusercontent.com/663949/43268521-788d36c0-9123-11e8-8364-7e1b8fdb7ac0.png)

**Expect**
http redirect to https

**Actual**
http not redirect to http yet

**Comment by jimcavoli** [comment]
This appears to be resolved; requests to the http version 301 to the https version.
