### ISSUE TITLE
Every gem needs a prominent link to its GitHub page

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-rb.org#28]
Right now there's no way to get from a gem's page on the dry-rb site through to its source code, issues, etc. on GitHub. I think we need to make this a fairly prominent link somewhere. Something with a special style at the bottom of each gem's navigation menu, perhaps?

**Comment by timriley** [comment]
It might actually be good to have a standard place for a series of "off-site" links, like GitHub, RubyGems.org, Travis, etc.

**Comment by solnic** [comment]
I was thinking about adding badges to intro pages like we have in readmes

**Comment by timriley** [comment]
I think the badges would be nice, but it would still be good to have some kind of prominent off-site links that are actually integrated into our gem page designs. The two could complement each other anyway.

**Comment by solnic** [comment]
yeah I would prefer that, I just thought copying badges from readmes would've been a quick-win for now :) it'd be awesome if we could come up with a nicer solution though

**Comment by GustavoCaso** [comment]
@timriley @solnic I'll be happy to provide such link in each gem page, we can place it in the bottom of gem page, the link could be the GitHub logo 
![image](https://cloud.githubusercontent.com/assets/4672858/23448588/31f4a690-fe52-11e6-9f08-b92fc6608ba2.png)

Is that ok ?

**Comment by flash-gordon** [comment]
Well, we need to do it folks. Is that GH logo OK?

**Comment by timriley** [comment]
I wonder if @makenosound or @jasminwong have any thoughts on this?

**Comment by makenosound** [comment]
There’s a lot of room in the header for each gem, so we could do something like:

![screen shot 2017-05-01 at 9 19 54 am](https://cloud.githubusercontent.com/assets/4353/25568839/55403650-2e4f-11e7-9a59-d1d5a109358e.png)

(with a badge)

**Comment by timriley** [comment]
@makenosound This looks good to me 👍

**Comment by GustavoCaso** [comment]
@flash-gordon should we close this one?

**Comment by solnic** [comment]
yes, but somebody needs to deploy new site first :D

**Comment by GustavoCaso** [comment]
@solnic I can deploy it :D

**Comment by GustavoCaso** [comment]
Done

**Comment by flash-gordon** [comment]
thanks @GustavoCaso 🎉
