### ISSUE TITLE
Documentation for dry-schema mentions a non existing class

### ISSUE THREAD

**Issue by klaustopher** [dry-rb/dry-rb.org#284]
In the section about defining about [Defining Base Schema Class](https://dry-rb.org/gems/dry-schema/basics/working-with-schemas/#defining-base-schema-class) it is mentioned that you can inherit from a `Dry::Schema::Schema` class.

Should this be, that you inherit from `Dry::Schema::JSON` or `Dry::Schema::Params`?

**Comment by flash-gordon** [comment]
@solnic we don't seem to have class-based inheritance in dry-schema

**Comment by klaustopher** [comment]
Fixed with 03e3e82875f74c9bb9c044a64f89f833a6a04772

**Comment by solnic** [comment]
> @solnic we don't seem to have class-based inheritance in dry-schema

we do, see https://dry-rb.org/gems/dry-schema/basics/working-with-schemas/
