### ISSUE TITLE
Entire blog post preview area on homepage should be a link

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-rb.org#30]
We should allow a click on any part of the blog post previews on the homepage to take the user through to the full post's page.

**Comment by andyicelab** [comment]
Given we allow anchor links in the summary paragraph this isn't currently possible. The two options I see are:

1) Make everything _else_ a link (the title and date) or;
2) Sanitize the home page summary paragraph and remove any anchor links

Given this is a preview and we want people to click through and read, my inclination is option 2).

**Comment by timriley** [comment]
Yep, (2) sounds good.

**Comment by timriley** [comment]
Fixed by #41
