### ISSUE TITLE
Documentation issue: Dry::Validation.Schema 

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-rb.org#312]
The docs are using `Dry::Validation.Schema`, which doesn't exist in dry-validation, but it has `Dry::Validation.Contract`

Is it an issue in the docs or it's supposed to have `Dry::Validation.Schema`?

```ruby
schema = Dry::Validation.Schema do
  required(:email).filled(:str?)
  required(:age).filled(:int?, gt?: 18)
end

# => NoMethodError: undefined method `Schema' for Dry::Validation:Module
```

```ruby
Dry::Validation::VERSION
=> "1.0.0"
```

**Comment by flash-gordon** [comment]
`Dry::Validation.Schema` is pre-1.0 DSL. Mind to point out where it's still referenced?

P.S. Please use this repo for issues about documentation. Also, if you're not sure if it's a bug/something else is wrong, please use our forum or chat, we normally use GH for tracking bugs and prediscussed feature requests.

**Comment by Morozzzko** [comment]
I think it's still easy to navigate when you enter `dry-validation` docs at https://dry-rb.org/gems/dry-validation/

It's probably because the URL generation has been refactored aaaand the feature broke. 

I'll add some specs to improve the navigation and make sure people don't follow the old links

**Comment by flash-gordon** [comment]
@Morozzzko well, old links are old, it happens things become outdated, we cannot control everything. I don't think we need specs for this, fixing the navigation part should be more than enough. I would simply add a heads up banner on the top.

**Comment by ndan** [comment]
@flash-gordon Look at the screenshot below, it shows the wrong version.

https://dry-rb.org/gems/dry-validation should definitely point to the latest version (like it does https://dry-rb.org/gems/dry-monads/)

<img width="1063" alt="Screen Shot 2019-06-11 at 10 29 52 PM" src="https://user-images.githubusercontent.com/760394/59300746-9e48ce80-8c98-11e9-8fa7-7f6dc8cd115c.png">

<img width="1043" alt="Screen Shot 2019-06-11 at 10 36 20 PM" src="https://user-images.githubusercontent.com/760394/59301053-642bfc80-8c99-11e9-84cb-25fda027915f.png">

**Comment by Morozzzko** [comment]
@flash-gordon  I mean, when the template generates the link to a page, it has to behave in a specific way. It worked for a while, and now it's broken. I want to fix & test this exact part of the navigation.

I'm saying something about the specs like:

1. If someone navigates to the old (unversioned) documentation links, all the links point towards the `current` docs
2. If someone decides to navigate around the _old_ API, all the links are permanent (= versioned)

That's what I was thinking, and that should be enough

**Comment by solnic** [comment]
I'm very very confused. I reverted the change where I made 1.0.0 the default in order to preserve previous URLs and my intention was to use explicit version URLs. It looked like it worked when I tested it so I'm not sure what's happening now 😞

**Comment by solnic** [comment]
OK I get it now, version switcher showed `1.0.0` despite the fact you were looking at `0.13` docs. I made `1.0.0` the default again so this is now fixed. Old URLs will break, but I guess search engines will just reindex the page eventually and it'll be fine. It is what it is.
