### ISSUE TITLE
Error in `Dry::Monads::Validated` examples

### ISSUE THREAD

**Issue by cgeorgii** [dry-rb/dry-rb.org#343]
The following code from the `Dry::Monads::Validated` [documentation](https://dry-rb.org/gems/dry-monads/validated/) appears to be incorrect, or at least unclear. The first validation method `validate_name` returns either `Valid(name)` or `Invalid(:invalid_name)`. The subsequent validation methods are said to return either `Success(email)` or `Invalid(email)`. These return types are inconsistent.

It's unclear from the documentation whether it is possible to return a `Dry::Monads::Result` directly from the validation method or not and could cause confusion. I would add that it should _not_ be possible to do so and the documentation should make it clear that either `Valid` or `Invalid` are the expected return types.

```ruby
require 'dry/monads'

class CreateAccount
  include Dry::Monads[:list, :result, :validated, :do]

  def call(form)
    name, email, password = yield List::Validated[
      validate_name(form),
      validate_email(form),
      validate_password(form)
    ].traverse.to_result

    user = repo.create_user(
      name: name,
      email: email,
      password: password
    )

    Success(user)
  end

  def validate_name(form)
    # Valid(name) or Invalid(:invalid_name)
  end

  def validate_email(form)
    # Success(email) or Invalid(:invalid_email)
  end

  def validate_password(form)
    # Success(password) or Invalid(:invalid_password)
  end
end
```

**Comment by flash-gordon** [comment]
Good catch. Yes, it's a mistake in the documentation. Feel free to send a PR or I'll fix it sometime later

**Comment by solnic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Trusted by" section on main page?](https://trello.com/c/8enXersM/17-trusted-by-section-on-main-page)
