### ISSUE TITLE
Adding the version to URLs broke some links, getting 404s

### ISSUE THREAD

**Issue by acdebaca** [dry-rb/dry-rb.org#360]
Example: https://dry-rb.org/gems/dry-schema/1.0/

The menu on the left under Advanced/Filtering correctly links to
```
https://dry-rb.org/gems/dry-schema/1.0/advanced/filtering
```

However in the main document section "Unique Features", the linked text "Pre-coercion validation using filtering rules" is still linked to the old URL:
```
https://dry-rb.org/gems/dry-schema/advanced/filtering
```
...which returns 404 as "1.0" is omitted from the path.

I'm guessing either the link target should have been automatically corrected on render as the menu links are, or the service should return a redirect at the old path instead of 404?

**Comment by solnic** [comment]
Thanks for the bug report. I'll fix it.

**Comment by solnic** [comment]
This is now fixed.
