### ISSUE TITLE
Embed twitter feed on home page and news pages

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-rb.org#37]

**Comment by andyicelab** [comment]
Hey @jasminwong — just wanted to check whether you had any design options about placement/style for this (and #36)?

**Comment by jasminwong** [comment]
@andyicelab I think we could comfortably shift the news listing to the left, and put a twitter feed in on the right. What do you think?

**Comment by andyicelab** [comment]
@jasminwong Yep, I like that idea. And I can imagine some share links at the bottom of the news/doc pages.

**Comment by andyicelab** [comment]
@jasminwong— here's an example using the official Twitter widget:

![dry-rb-twitter-feed](https://cloud.githubusercontent.com/assets/1016074/13975488/11f70d52-f10a-11e5-81f5-48c0f91f113e.jpg)

**Comment by jasminwong** [comment]
Thanks @andyicelab! Hmm, I think the "News" header should be removed.
