### ISSUE TITLE
Missing documentation for version 1.0 +

### ISSUE THREAD

**Issue by AlexeyBoldak** [dry-rb/dry-rb.org#375]
I found that on [https://dry-rb.org/gems/dry-validation/1.0/](https://dry-rb.org/gems/dry-validation/1.0/) and later versions you provide a lot less documentation than in the previous one [https://dry-rb.org/gems/dry-validation/0.13/](https://dry-rb.org/gems/dry-validation/0.13/) Is it expected?

**Comment by flash-gordon** [comment]
It is because most of its features were extracted to dry-schema. Please read the announcement https://dry-rb.org/news/2019/06/10/dry-validation-1-0-0-released/ It contains links to dry-schema and the upgrade guide.

**Comment by AlexeyBoldak** [comment]
Thanks!
