### ISSUE TITLE
`dry-cli` commands with subcommands and params page is downloaded instead of being opened by the browser

### ISSUE THREAD

**Issue by vikdotdev** [dry-rb/dry-rb.org#399]
Here's that page https://dry-rb.org/gems/dry-cli/1.0/commands-with-subcommands-and-params

Server responds with `content-type: application/octet-stream` only for this one page.

**Comment by Xavier-IV** [comment]
Hey, this is addressed in these PRs:

V1.0:
- https://github.com/dry-rb/dry-cli/pull/127
- https://github.com/dry-rb/dry-cli/pull/130

V0.7 (also affected):
- https://github.com/dry-rb/dry-cli/pull/132

**Comment by timriley** [comment]
Thank you both! I'll look to apply these today.

**Comment by timriley** [comment]
Fixed by https://github.com/dry-rb/dry-cli/pull/127.

Will do a docs rebuild soon.
