### ISSUE TITLE
dry-validation documentation errors

### ISSUE THREAD

**Issue by ingobecker** [dry-rb/dry-rb.org#54]
While reading the documentation of dry-validation i stumbled upon some things that seem stange to me:
- What's `good_input` handed to `schema.call()` in section [none?](https://github.com/dry-rb/dry-rb.org/blob/master/source/gems/dry-validation/basics/built-in-predicates.html.md#none)?
- In section [eql?](https://github.com/dry-rb/dry-rb.org/blob/master/source/gems/dry-validation/basics/built-in-predicates.html.md#eql) should it be `assert input[:sample] == 1234` instead of `assert sample[:input] == 1234`?
- Again, `good_input` in section [type?](https://github.com/dry-rb/dry-rb.org/blob/master/source/gems/dry-validation/basics/built-in-predicates.html.md#type) instead of just `input`?

**Comment by timriley** [comment]
Thanks for the report, @ingobecker. 

* I think `good_input` is meant to be `input` in the `none?` example.
* Your suggestion for the `eql?` code example is correct :)
* And yes, `good_input` should just be `input` in the `type?` example too.

Are you happy to go ahead and make these changes? I'll merge 'em right in :)

**Comment by ingobecker** [comment]
Created a pull request: #58

**Comment by apohllo** [comment]
Since the PR was merged, maybe the issue should be closed as well?

**Comment by flash-gordon** [comment]
aaaand done!
