### ISSUE TITLE
dry-validation documentation

### ISSUE THREAD

**Issue by saverio-kantox** [dry-rb/dry-rb.org#72]
in page https://github.com/dry-rb/dry-rb.org/blob/master/source/gems/dry-validation/high-level-rules.html.md there is something that seems incorrect:

``` ruby
rule(barcode_only: [:barcode, :job_number, :sample_number]) do |barcode, job_num, sample_num|
  barcode.filled? & (job_num.none? & sample_num.none?)
end
```

is put as an example of "validating absence of `job_num` and `sample_num` **when** `barcode` is filled". But to me the code sounds as "validating absence of `job_num` and `sample_num` **and** `barcode` is filled". Maybe it was supposed to be as follows?

``` ruby
rule(barcode_only: [:barcode, :job_number, :sample_number]) do |barcode, job_num, sample_num|
  barcode.empty? | (job_num.none? & sample_num.none?)
end
```

**Comment by apohllo** [comment]
It was fixed - the operator is `>` now. The issue could be closed.
